[tool.poetry]
name = "silvia_control"
version = "0.1.0"
description = ""
authors = ["Robert"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
nicegui = "^1.4.5"
pigpio = "^1.78"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
